[package]
name = "drawio-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5"
clap = { version = "4.5.20", features = ["derive"] }
snafu = "0.8.5"
regex = "1.11.0"