name: Rust CI

on:
  push:
    branches:
      - '**' # Runs on every branch commit
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
      fail-fast: false # Allows other jobs to complete even if one fails

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}

    - name: Cache Cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: cargo-index-${{ runner.os }}
        restore-keys: |
          cargo-index-${{ runner.os }}

    - name: Build project
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose